### DISCUSSION TITLE
Update - Voice assistant possible fix!

### DISCUSSION THREAD

**Discussion by BigBobbas** [BigBobbas/ESP32-S3-Box3-Custom-ESPHome#10] [Announcements]
Hi Guys, I have made some amendments that hopefully will sort out VA not responding. I have tested and am able to send multiple commands and also leave and go back to it and it responds. so hopefully this will help.  you can just add this to the existing voice_assistant: config.
```yaml
  on_end:
    - if:
        condition:
          lambda: return id(wake_word_engine_location).state == "On device";
        then:
          - wait_until:
              not:
                voice_assistant.is_running:
          - micro_wake_word.start
        else:
          - wait_until:
              not:
                voice_assistant.is_running:
          - lambda: id(va).set_use_wake_word(false);
          - voice_assistant.stop:    
          - delay: 100ms
          - lambda: id(va).set_use_wake_word(true);
          - delay: 100ms
          - voice_assistant.start_continuous: 
         
```

replacing the current on_end: section.
