### DISCUSSION TITLE
Latency on changing state of lights

### DISCUSSION THREAD

**Discussion by jerome6994** [BigBobbas/ESP32-S3-Box3-Custom-ESPHome#107] [General]
Good evening
I discovered the S3-Box with your improvement and Home assistant.
This is remarkable work, well done.

I put two lights on the lights page.
When I select a light it turns the light on but the icon takes a long time to switch to ON light! It's the same when I turn off the light!
It's as if the screen is not refreshing because when I click on another light bulb where nothing is planned then it changes the icon of the previous light !
The change of state on the bulb icon can occur 10/12 seconds later
Did I miss anything in the code ?

Thanking you for your insights because I must be missing something

Jérôme 

```
  - platform: homeassistant
    id: ecl_baie_led_haut
    entity_id: light.ecl_baie_led_haut
    internal: true
```

```
 - platform: touchscreen
    page_id: lights_page
    id: lights2
    internal: true
    x_min: 110
    x_max: 210
    y_min: 90
    y_max: 170
          #### make sure that the following 4 lines are uncommented by removing the prefixed '#' ###
    on_click:
      min_length: 10ms
      max_length: 500ms
      then: 
        - homeassistant.service:
            service: light.toggle
            data:
              entity_id: light.ecl_baie_led_haut
      #### add your action here - make sure to uncomment the following  line by removing the prefixed '#' and keep these below your action #####
        - component.update: s3_box_lcd
```

 ```
 if(id(ecl_baie_led_bas).state == "on") {
         it.printf(20, 75, id(icon_font_80), yellow,"\U000F06E8");  
  } else {
         it.printf(20, 75, id(icon_font_80), light_blue,"\U000F0335" ); 
  }
  it.printf(20, 135, id(my_font3), white, "Bas");
```

**Comment by BigBobbas** [comment]
Hi,
the `id:` in this block should be `ecl_baie_led_haut` 
![image](https://github.com/user-attachments/assets/be41c126-6212-43be-b376-77cb76f4f0d5)
hopefully that will fix it 👍 

Many Thanks
Rob

**Comment by jerome6994** [comment]
Good morning
Thanks for the answer but I think I did a stupid copy/paste because I have two lights up and down!

If necessary, but I don't know if it fits here I have a short 1 minute video showing the phenomenon

here they are :
 
 ```
- platform: homeassistant
    id: ecl_baie_led_haut
    entity_id: light.ecl_baie_led_haut
    internal: true

  - platform: homeassistant
    id: ecl_baie_led_bas
    entity_id: light.ecl_baie_led_bas
    internal: true
  
  - platform: homeassistant
    id: temp_baie_temperature
    entity_id: sensor.temp_baie_temperature
    internal: true


```

   ```
 if(id(ecl_baie_led_bas).state == "on") {
            it.printf(20, 75, id(icon_font_80), yellow,"\U000F06E8");  
    } else {
            it.printf(20, 75, id(icon_font_80), light_blue,"\U000F0335" ); 
    }
    it.printf(20, 135, id(my_font3), white, "Bas");

    if(id(ecl_baie_led_haut).state == "on") {
            it.printf(120, 75, id(icon_font_80), yellow,"\U000F06E8");  
    } else {
            it.printf(120, 75, id(icon_font_80), light_blue,"\U000F0335" ); 
    }
    it.printf(120, 135, id(my_font3), white, "Haut");

```

```
##### lights page #####  
  - platform: touchscreen
    page_id: lights_page
    id: lights1
    internal: true
    x_min: 5
    x_max: 105
    y_min: 90
    y_max: 170
          #### make sure that the following 4 lines are uncommented by removing the prefixed '#' ###
    on_click:
      min_length: 10ms
      max_length: 500ms
      then:
        - homeassistant.service:
            service: light.toggle
            data:
              entity_id: light.ecl_baie_led_bas
      #### add your action here - make sure to uncomment the following  line by removing the prefixed '#' and keep these below your action #####
        - component.update: s3_box_lcd

  - platform: touchscreen
    page_id: lights_page
    id: lights2
    internal: true
    x_min: 110
    x_max: 210
    y_min: 90
    y_max: 170
          #### make sure that the following 4 lines are uncommented by removing the prefixed '#' ###
    on_click:
      min_length: 10ms
      max_length: 500ms
      then: 
        - homeassistant.service:
            service: light.toggle
            data:
              entity_id: light.ecl_baie_led_haut
      #### add your action here - make sure to uncomment the following  line by removing the prefixed '#' and keep these below your action #####
        - component.update: s3_box_lcd
```

**Reply by BigBobbas** [reply]
hi, Good Morning.
Do you have the following (below), under the `text_sensor:` or `sensor:` section?
```
- platform: homeassistant
   id: ecl_baie_led_haut
   entity_id: light.ecl_baie_led_haut
   internal: true

 - platform: homeassistant
   id: ecl_baie_led_bas
   entity_id: light.ecl_baie_led_bas
   internal: true
   ```

**Comment by jerome6994** [comment]
I have this under the text_sensor section

**Comment by joopdehoop** [comment]
Hey Jerome, not sure if you're already found your answer, but I was struggling with the same issue and was finally able to fix it by adding the following to the sensors:

```
 - platform: homeassistant
   id: ecl_baie_led_bas
   entity_id: light.ecl_baie_led_bas
   internal: true
   on_value:
     - component.update: s3_box_lcd
```

Hope that helps!
