### DISCUSSION TITLE
Set limit to timer off beeps

### DISCUSSION THREAD

**Discussion by bouton** [BigBobbas/ESP32-S3-Box3-Custom-ESPHome#109] [General]
I am trying to set the sbox3 such that when the timer ends the beeps only go off for x # of times, (or for a set time after).  I have set a repeat/count in front of the timer_started_external script homeassistant.service but that loops endlessly.

Any hints.

I know I can yell 'timer cancel' but I would like even to not have to do that. 

This is fabulous by the way. First time I have had an understanding of how esphome works.

**Comment by BigBobbas** [comment]
Hi there ,
the duration of the timer sound is actually set using a delay in the following `switch:` with the default at 15mins. so you can can change that to whatever you choose. or you could remove the delay and as put a count in your script as you mentioned. Basically the script runs until the switch is turned off as it currently stands. 
I hope that helps 👍 

```yaml
  - platform: template
    id: timer_ringing
    optimistic: true
    internal: true
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - lambda: id(led).turn_on().set_brightness(1.0).perform();
      - delay: 15min
      - switch.turn_off: timer_ringing 
    on_turn_off:
      - media_player.stop
      ```

**Reply by bouton** [reply]
Duh - how did I miss that.  Thanks for the quick reply.

**Reply by bouton** [reply]
PS - changing delay time worked just fine. Thanks.

**Comment by BigBobbas** [comment]
glad you got it sorted 👍

**Comment by bouton** [comment]
Continuing with timer...
I am trying to set a timer, have it go to the timer coundown age and stay on the countdown page until finished.

timer_started goes to script timer_ending which has a wait until 10 sec then go to time_remaining age.  I want it to go to the time_remaining_page and stay there until countdown is finished.
I comment out the wait_until but no luck. That only sent me to the screensave page until time was done and I got the timer finished page.

I can't seem to get to the time_remaining_page and stay there throughout the whole thing.
Any hints welcome

Thanks

**Comment by BigBobbas** [comment]
Hi there ,
I can't test it right now,
but you could try something along the lines of ........
under `script:` change the `timer_ending` script to something like this
```yaml
  - id: timer_ending
    then:
      - if:
          condition: 
            - lambda: return (id(time_remaining_0).state => "0:00:00");
      - script.stop: saver_enabled
      - display.page.show: time_remaining_page
      - component.update: s3_box_lcd      
      ```
      I think that should be close to what you need.
