### DISCUSSION TITLE
Customise day and month names to match your local language

### DISCUSSION THREAD

**Discussion by BigBobbas** [BigBobbas/ESP32-S3-Box3-Custom-ESPHome#11] [Announcements]
Hi Guys,
I have added the option to change what is displayed for day and month, please see the message here for details [Change displayed day and month](<https://github.com/BigBobbas/ESP32-S3-Box3-Custom-ESPHome/discussions/9#discussioncomment-9817662>)
This is not yet added to the main install file or the manual config file s3b.yaml but will be included on the next updated version.
Hope this helps 
Cheers 
Rob

**Comment by Bluhme1** [comment]
This works great. I have customised the saver page to my needs.
I live in Denmark and we have 3 more letters in the alphabet "æ", "ø" and "å" "ø" is being used in our weekdays lørdag (Saturday) and søndag (Sunday). Now we are on a Saturday and I can se that on my screen I am missing the letter "ø"

I think @jaymunro have solved that in his "continuous conversation" firmware

Maybe it can also be included in your version

thanks in advance

/Lars

**Reply by BigBobbas** [reply]
Hi,
under `font:` you can add the glyphs line to each of the fonts that you wish for these to display.
For the date on the screen save page this uses `my_font3` so if you add the bottom line this should then display these characters.
```yaml
  - file: "https://github.com/BigBobbas/ESP32-S3-Box3-Custom-ESPHome/raw/main/fonts/consola.ttf"
    id: my_font3
    size: 28
    glyphs: ["æ","ø","å","ø"]
```
