### DISCUSSION TITLE
Dynamic sensor updates on value change

### DISCUSSION THREAD

**Discussion by TheSerapher** [BigBobbas/ESP32-S3-Box3-Custom-ESPHome#112] [Q&A]
Hey Community,

First off, great work on this project! My Box was sitting around most of the time since I was missing some additional features out of the box like displaying sensor values. This project finally allowed me to do just that!

Question that came up after implementing a simple page for Solar Production and Power Consumption:

How can I refresh the sensor data from Home Assistant only when I am actually looking at the page for the sensors? I re-purposed the `template_page` as `solar_page` and added the sensors to the `text_sensors` block and the details onto that page (see code below). Now everything seems to work just fine but after installing this I also noticed how often the data is updated (once for each sensors value change). Of course I could just limit it to the consumption sensor since it will certainly always update but that felt wrong. Especially since the sensors constantly update in the background.

Q: How can I either throttle the updates on the sensor, disable updates of sensor values unless I am in the page or otherwise reduce the amount of updates?

Any help is appreciated 😄 

**Page**
```
      - id: solar_page ##### solar page ####
        lambda: |-
          it.fill(id(black));
          it.printf(20, 22, id(my_font5), white, TextAlign::LEFT, "Production:");
          it.printf(315, 75, id(my_font2), white, TextAlign::RIGHT, "%s", id(solar_production).state.c_str());
          it.printf(20, 128, id(my_font5), white, TextAlign::LEFT, "Consumption:");
          it.printf(315, 181, id(my_font2), white, TextAlign::RIGHT, "%s", id(power_consumption).state.c_str());
```

**Sensor**

```
text_sensor:
  - platform: homeassistant
    entity_id: sensor.fems_production_active_power
    name: "Solar Production"
    id: solar_production
    internal: true
    on_value:
      component.update: s3_box_lcd    
  - platform: homeassistant
    entity_id: sensor.fems_consumption_active_power
    name: "Power Consumption"
    id: power_consumption
    internal: true
    on_value:
      component.update: s3_box_lcd  
```
