### DISCUSSION TITLE
TESTERS REQUIRED - ESPHome 2025.2.x - removed esp ADF Components

### DISCUSSION THREAD

**Discussion by BigBobbas** [BigBobbas/ESP32-S3-Box3-Custom-ESPHome#128] [Announcements]
hi everyone, I have added the new ESPHome media player and removed the ADF external component. It is working for me... but if anyone would like to test and find the bugs,  then we can take it from there  
I've put a sensor and no sensor dock version here https://github.com/BigBobbas/ESP32-S3-Box3-Custom-ESPHome/tree/dev
The best place to get involved and give feedback, report issues etc is on Discord https://discord.gg/U3SRYCG6Kp

Many Thanks as always for your support 👍

**Comment by smartmatic** [comment]
Hi @BigBobbas 
I've installed the dev branch which worked without issues. Thank you.
Then i've configured a light in the lights page but the light does not switch on.

I see only this in the logs

```
08:45:10][D][binary_sensor:036]: 'lights1': Sending state ON
[08:45:10][D][script:077]: Script 'saver_enabled' restarting (mode: restart)
[08:45:10][D][light:036]: 'LCD Backlight' Setting:
[08:45:10][D][light:051]:   Brightness: 100%
[08:45:10][D][light:085]:   Transition length: 0.1s
[08:45:10][D][binary_sensor:036]: 'lights1': Sending state OFF
```

This is my configuration:

```
#### lights page #####  
  - platform: touchscreen
    page_id: lights_page
    id: lights1
    internal: true
    x_min: 5
    x_max: 105
    y_min: 90
    y_max: 170
          #### make sure that the following 4 lines are uncommented by removing the prefixed '#' ###
    on_click:
      min_length: 10ms
      max_length: 500ms
      then: 
        - homeassistant.service:
            service: light.toggle
            data:
              entity_id: light.schlafzimmer_deckenlicht
 
        - component.update: s3_box_lcd
```

Do i made something wrong?
