### DISCUSSION TITLE
*** BREAKING CHANGE ESPhome 2024.6.0 ****

### DISCUSSION THREAD

**Discussion by BigBobbas** [BigBobbas/ESP32-S3-Box3-Custom-ESPHome#13] [Announcements]
IN the latest release of ESPHome 2024.6.0 there have been changes to the way that OTA: needs to be configured.  I will update the main config files to reflect this.
IF you are running into problems with compiling with this version please see the note below:
you will need to use ONE of the following to be able to compile.
```yaml
# Old method without password
ota:

# Old method with password
ota:
  password: "xxxx"

# New method without password
ota:
  platform: esphome

# New method with password
ota:
  platform: esphome
  password: "xxxx"
  ```
  basically you need to at minimum add the platform line below `ota:` this is indented by 2 spaces from the left. The default for the configs is with out password. so changing to the below , should be all that is required.
  ```yaml
  ota:
    platform: esphome
```
Thanks as ever

Rob
