### DISCUSSION TITLE
How can i push a helper-button in ha

### DISCUSSION THREAD

**Discussion by Tobi9111** [BigBobbas/ESP32-S3-Box3-Custom-ESPHome#138] [Q&A] [answered]
Hi,
I'm currently stuck on a small issue...

I want to press a "helper"-button in HomeAssistant with a touch botton on the s3-box3. Unfortunately, so far, it hasn't worked with buttons for me, only with switches and lights. Here's my code for the relevant location on the touchscreen:

```
- platform: touchscreen
    page_id: template_page
    id: template1
    internal: true
    x_min: 5
    x_max: 105
    y_min: 90
    y_max: 170
    on_click:
      min_length: 10ms
      max_length: 500ms
      then:
        - homeassistant.service:
            service: switch.toggle
            data:
              entity_id: input_button.heizungsautomatisierung
```

and i try:
...
```
      then:
        - homeassistant.service:
            action: button.press
            data:
              entity_id: input_button.heizungsautomatisierung

```
both doesn´t work and i get the following warning in the ha logs:

```
Logger: homeassistant.helpers.service
Quelle: helpers/service.py:304
Erstmals aufgetreten: 11:38:13 (9 Vorkommnisse)
Zuletzt protokolliert: 13:20:00

Referenced entities input_button.heizungsautomatisierung are missing or not currently available
```

I double checked the entitie-id. The id is definitly correct.

Thanks in andvance for support and best regards!
Tobi

**Comment by BigBobbas** [comment, marked as answer]
Hi 
the action you need, would be `input_button.press`
the following should work 👍 
```yaml
      then:
        - homeassistant.service:
            action: input_button.press
            data:
              entity_id: input_button.heizungsautomatisierung
```
