### DISCUSSION TITLE
Fahrenheit

### DISCUSSION THREAD

**Discussion by geddyleefan** [BigBobbas/ESP32-S3-Box3-Custom-ESPHome#33] [Ideas]
I searched and didn't find what I was looking for here, so I made my own changes to display the temperature in F and thought I'd post in case anyone else found it useful. I changed my sensor section to this:

```
sensor:
  - platform: aht10
    i2c_id: bus_b
    variant: AHT20
    temperature:
      filters:
        - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"
      name: "Temperature"
      id: s3temp
    humidity:
      name: "Humidity"
    update_interval: 60s
```
I'm not great at things like that, so thanks Reddit :)

And changed this line:
it.printf(160, 180, id(my_fontseg2), light_blue, TextAlign::CENTER, "%.f°C", id(s3temp).state);
to this:
it.printf(160, 180, id(my_fontseg2), light_blue, TextAlign::CENTER, "%.f°F", id(s3temp).state);

It would be nice to have a way to switch from C to F without having to modify the YAML on your own though. Next, I'll figure out 12-hour time, that would also be a nice option to have.

Also, this project is awesome! Thank you so much BigBobbas, I'm really enjoying having this on my Box-3.

**Comment by BigBobbas** [comment]
Hi, thanks for your support! 
I saw rush in the UK in the late 80's - Awesome experience. 👍 thought i would get that out of the way first!

That's a great tip regarding the temp ... I will be updating the docs in the next day or so. and am hoping to add an update to the config later today to add timers, wake sound (can turn on and off from the device)  also a few other enhancements and tweaks.

I will see if there is a way to implement these so we can add a button in the setting page, if I can't figure it (or anyone else) then I will add your workaround to the docs and also the 12hr as both would be a nice addition.

Cheers
Rob

**Comment by MetalOnes** [comment]
> Next, I'll figure out 12-hour time, that would also be a nice option to have.

I customized my saver_page to have 12hr time, as well as show a second temperature (note that I'm using sensors from HASS, not the onboard temp sensor).

```
- id: saver_page
  lambda: |-
    it.fill(Color::BLACK);
    it.strftime(160, 20, id(my_font3), light_grey, TextAlign::CENTER, "%A %d %b", id(ha_time).now());
    it.strftime(160, 82, id(my_fontseg2), blue_drk, TextAlign::CENTER, "%l:%M", id(ha_time).now());
    it.strftime(160, 155, id(my_fontseg4), blue_drk, TextAlign::CENTER, "%p", id(ha_time).now());
    it.printf(10, 230, id(my_fontseg3), purple, TextAlign::BOTTOM_LEFT, "%.f°", id(mc_temp).state);
    it.printf(310, 230, id(my_fontseg3), green_drk, TextAlign::BOTTOM_RIGHT, "%.f°", id(outdoor_temp).state);
```

![image](https://github.com/BigBobbas/ESP32-S3-Box3-Custom-ESPHome/assets/28925077/02e4aec9-9e4e-49d3-a2cc-7186978acbe0)

**Reply by IdiotTryingToFindWay** [reply]
I tried doing that with your code and added the extra my_fontseg3  etc and i get 
![Screenshot 2024-07-03 214007](https://github.com/BigBobbas/ESP32-S3-Box3-Custom-ESPHome/assets/148826647/ae848d5e-740c-4267-9d13-a8a582d1ead5)
what am i not adding because i like that setup

**Reply by BigBobbas** [reply]
my_fontseg3 and my_fontseg4 need to be added under the `font: ` block. you can do this by copying and pasting my_fontseg then renaming and changing the font 'size' . I am not sure what size was used, but you could try sample below and then tweak to suit.
so something like: 
```yaml  
- file: "https://github.com/BigBobbas/ESP32-S3-Box3-Custom-ESPHome/raw/main/fonts/DSEG7Classic-Regular.ttf"
    id: my_fontseg3
    size: 30
 - file: "https://github.com/BigBobbas/ESP32-S3-Box3-Custom-ESPHome/raw/main/fonts/DSEG7Classic-Regular.ttf"
    id: my_fontseg4
    size: 50
  ```

**Reply by IdiotTryingToFindWay** [reply]
where do you suppose he's putting those id's?
id(mc_temp).state);
 id(outdoor_temp).state);

And btw is there a way to make the screen saver brighter?

**Reply by BigBobbas** [reply]
those id's will be from sensors added from HA you would need to add your own sensors and give them id:'s to suit. 
if you look at the instruction guide here https://github.com/BigBobbas/ESP32-S3-Box3-Custom-

ESPHome/blob/main/instructions/make%20it%20your%20own.md#displaying-sensor-information
it shows how to add sensors from HA you can then use those id's on the 'saver_page` instead of the default onboard sensor.

To change the brightness.
look in the yaml under the `script:` block and you can change the value from `brightness: 30%` to whatever you wish.
```yaml
  - id: saver_enabled_manual
    then:
      - if:
          condition: 
            switch.is_on: s_saver 
          then:
            - light.turn_on: 
                id: led
                brightness: 30%
            - display.page.show: saver_page
            - component.update: s3_box_lcd
      - if:
          condition:
            - switch.is_on: s_saver_mode            
          then:
            - delay: 180s
            - light.turn_off: led
    mode: restart 
```
I hope this helps.

Cheers 

Rob

**Reply by IdiotTryingToFindWay** [reply]
ok i got that figured out now, thank you. but for the humidity sensor i get an error with this. i'm assuming "%.", is breaking it. not sure what to put there tbh so i guessed lol

/config/esphome/esphome-web-0503cc.yaml:1281:72: error: conversion lacks type at end of format [-Werror=format=]
           it.printf(310, 230, id(my_fontseg3), amber, TextAlign::BOTTOM_RIGHT, "%.", id(humid).state);
                                                                        ^~~~
/config/esphome/esphome-web-0503cc.yaml:1281:72: error: too many arguments for format [-Werror=format-extra-args]

**Reply by IdiotTryingToFindWay** [reply]
wait i figured it out reading esp docs

**Comment by MetalOnes** [comment]
My bad, here's the font definitions I used:
```
  - file: "https://github.com/BigBobbas/ESP32-S3-Box3-Custom-ESPHome/raw/main/fonts/DSEG14Classic-Regular.ttf"    
    id: my_fontseg
    size: 72

  - file: "https://github.com/BigBobbas/ESP32-S3-Box3-Custom-ESPHome/raw/main/fonts/DSEG7Classic-Regular.ttf"
    id: my_fontseg2
    size: 76

  - file: "https://github.com/BigBobbas/ESP32-S3-Box3-Custom-ESPHome/raw/main/fonts/DSEG7Classic-Regular.ttf"
    id: my_fontseg3
    size: 44
  
  - file: "https://github.com/BigBobbas/ESP32-S3-Box3-Custom-ESPHome/raw/main/fonts/DSEG14Classic-Regular.ttf"    
    id: my_fontseg4
    size: 40
```
> where do you suppose he's putting those id's?
> id(mc_temp).state);
> id(outdoor_temp).state);

Those are defined under sensors.
```
sensor:
  - platform: homeassistant
    id: mc_temp
    entity_id: sensor.man_cave_temperature
    internal: true

  - platform: homeassistant
    id: outdoor_temp
    entity_id: sensor.wupws_temp
    internal: true
```

**Comment by IdiotTryingToFindWay** [comment]
![20240704_171448](https://github.com/BigBobbas/ESP32-S3-Box3-Custom-ESPHome/assets/148826647/0cfda85b-bac5-4bd4-b5e8-cc03c7229983)

I added a tweak to it but it's working. I wish I could change the bar beside the humidity to a % but nothing I tried worked. I guess they use the bar for reference to humidity level just seems odd lol

**Reply by BigBobbas** [reply]
looking good 👍 You should be able to display % using "%.0f%%" in the display lamba ,  hope that works!

**Reply by youkorr** [reply]
I would be interested in publishing what you have modified

**Reply by IdiotTryingToFindWay** [reply]
I tried that and it didn't work for what ever reason

**Reply by IdiotTryingToFindWay** [reply]
- id: saver_page
        lambda: |-
          it.fill(Color::BLACK);
          it.strftime(160, 20, id(my_font3), light_blue, TextAlign::CENTER, "%A %d %b", id(ha_time).now());
          it.strftime(160, 82, id(my_fontseg2), light_blue, TextAlign::CENTER, "%l:%M", id(ha_time).now());
          it.strftime(160, 155, id(my_fontseg4), light_blue, TextAlign::CENTER, "%p", id(ha_time).now());
          it.printf(45, 170, id(my_font6), amber, TextAlign::BOTTOM_LEFT, "Home");
          it.printf(10, 190, id(my_font6), amber, TextAlign::BOTTOM_LEFT, "Temperature");
          it.printf(286, 170, id(my_font6), amber, TextAlign::BOTTOM_RIGHT, "Home");
          it.printf(305, 190, id(my_font6), amber, TextAlign::BOTTOM_RIGHT, "Humidity");
          it.printf(10, 230, id(my_fontseg3), green, TextAlign::BOTTOM_LEFT, "%.f°", id(liv_temp).state);
          it.printf(310, 230, id(my_fontseg3), green, TextAlign::BOTTOM_RIGHT, "%.0f%%", id(humid).state);

what i did was basically the previous post but just added some dumb text so it's easier to see which sensor your looking at. Think i might add dynamic now so you can see the battery level

**Reply by IdiotTryingToFindWay** [reply]
i added another font "my_font6" because i wanted to adjust the text size and wasn't sure if the previous was called on by a different tag. could have checked but was feeling lazy lol

**Reply by youkorr** [reply]
hello I tried to put your code but I got errors

      - id: saver_page
        lambda: |-
         it.fill(Color::BLACK);
         
         const char *days[] {"${sunday}","${monday}","${tuesday}","${wednesday}","${thursday}","${friday}","${saturday}"};
         it.printf(165, 10, id(my_font3), light_blue, TextAlign::RIGHT, days[id(ha_time).now().day_of_week - 1]);   
         
         it.strftime(180, 10, id(my_font3), light_blue, "%d", id(ha_time).now());
         
         const char *months[] {"${jan}","${feb}","${mar}","${apr}","${may}","${jun}","${jul}","${aug}","${sept}","${oct}","${nov}","${dec}"};
         it.printf(220, 10, id(my_font3), light_blue, TextAlign::LEFT, months[id(ha_time).now().month - 1]);
         
         it.strftime(160, 20, id(my_font3), light_blue, TextAlign::CENTER, "%A %d %b", id(ha_time).now());
         it.strftime(160, 82, id(my_fontseg2), light_blue, TextAlign::CENTER, "%l:%M", id(ha_time).now());
         it.strftime(160, 155, id(my_fontseg4), light_blue, TextAlign::CENTER, "%p", id(ha_time).now());
         it.printf(45, 170, id(my_font6), amber, TextAlign::BOTTOM_LEFT, "Home");
         it.printf(10, 190, id(my_font6), amber, TextAlign::BOTTOM_LEFT, "Temperature");
         it.printf(286, 170, id(my_font6), amber, TextAlign::BOTTOM_RIGHT, "Home");
         it.printf(305, 190, id(my_font6), amber, TextAlign::BOTTOM_RIGHT, "Humidity");
         it.printf(10, 230, id(my_fontseg3), green, TextAlign::BOTTOM_LEFT, "%.f°", id(liv_temp).state);
         it.printf(310, 230, id(my_fontseg3), green, TextAlign::BOTTOM_RIGHT, "%.0f%%", id(humid).state);

**Reply by youkorr** [reply]
I forgot to create my font 6 :)

**Reply by IdiotTryingToFindWay** [reply]
Add it exactly like MetalOnes did in his post. remove all the previous code under saver_page.

- id: saver_page
        lambda: |-
          it.fill(Color::BLACK);
          it.strftime(160, 20, id(my_font3), light_blue, TextAlign::CENTER, "%A %d %b", id(ha_time).now());
          it.strftime(160, 82, id(my_fontseg2), light_blue, TextAlign::CENTER, "%l:%M", id(ha_time).now());
          it.strftime(160, 155, id(my_fontseg4), light_blue, TextAlign::CENTER, "%p", id(ha_time).now());
          it.printf(45, 170, id(my_font6), amber, TextAlign::BOTTOM_LEFT, "Home");
          it.printf(10, 190, id(my_font6), amber, TextAlign::BOTTOM_LEFT, "Temperature");
          it.printf(286, 170, id(my_font6), amber, TextAlign::BOTTOM_RIGHT, "Home");
          it.printf(305, 190, id(my_font6), amber, TextAlign::BOTTOM_RIGHT, "Humidity");
          it.printf(10, 230, id(my_fontseg3), green, TextAlign::BOTTOM_LEFT, "%.f°", id(liv_temp).state);
          it.printf(310, 230, id(my_fontseg3), green, TextAlign::BOTTOM_RIGHT, "%.0f%%", id(humid).state);
And you are getting errors because you haven't created your sensors yet

- platform: homeassistant
    id: liv_temp
    entity_id: sensor.home_current_temperature
    internal: true  
  
- platform: homeassistant
    id: humid
    entity_id: sensor.home_current_humidity
    internal: true

Replace mine with the sensors you want from your HA. put that under sensor: section in your yaml

**Reply by youkorr** [reply]
ok

**Reply by youkorr** [reply]
my sensor was already created

**Reply by youkorr** [reply]
I'm going to start compiling

**Reply by youkorr** [reply]
my font6 is too big I have to reduce it

**Reply by youkorr** [reply]
It is true that the % does not work

**Reply by IdiotTryingToFindWay** [reply]
i'm trying something now to see if it fixes it. and it's only doing that for the humidity sensor not the temp

**Comment by BigBobbas** [comment]
if % isn't showing still try adding
```yaml
    glyphs:  '%'
  ``` 
  to the font you are using for humidity

**Reply by youkorr** [reply]
Or exactly ?

**Reply by BigBobbas** [reply]
example
```yaml
  - file: "https://github.com/BigBobbas/ESP32-S3-Box3-Custom-ESPHome/raw/main/fonts/DSEG7Classic-Regular.ttf"
    id: my_fontseg2
    glyphs: '%'
    size: 72
```

**Reply by youkorr** [reply]
ok thanks

**Reply by IdiotTryingToFindWay** [reply]
that actually broke it for me. temp and humidity has a solid bar representing now
and i'm getting errors in the log

[00:28:39][W][font:112]: Encountered character without representation in font: 'n'
[00:28:39][W][font:112]: Encountered character without representation in font: 'a'
[00:28:39][W][font:112]: Encountered character without representation in font: 'n'
[00:28:39][W][font:112]: Encountered character without representation in font: '\xc2'
[00:28:39][W][font:112]: Encountered character without representation in font: '\xb0'
[00:28:39][W][font:112]: Encountered character without representation in font: 'n'
[00:28:39][W][font:112]: Encountered character without representation in font: 'a'
[00:28:39][W][font:112]: Encountered character without representation in font: 'n

**Reply by youkorr** [reply]
patience

**Reply by BigBobbas** [reply]
looks like you have to add the whole range 
just had chance to test .. was guessing before lol 

'&@!"''%()+=,-_.:°/$€£¥?0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyzÀàÁáÂâÃãÄäĀāĂăÅåǺǻẠạĄąÆæǼǽĆćĈĉČčĊċÇçĎďĐđÐðÈèÉéÊêẼẽĚěËëĒēĔĕĖėẸẹĘęĜĝǦǧĞğĠġĢģĤĥĦħıÌìÍíÎîĨĩÏïĪīĬĭİỊịĮįȷĴĵĶķĸĹĺĽľĻļŁłĿŀŃńÑñŇňŅņƝɲŊŋŉÒòÓóÔôÕõÖöŌōŎŏŐőỌọǪǫØøǾǿŒœŔŕŘřŖŗŚśŜŝŠšŞşȘșẞßŤťŢţȚțŦŧÞþÙùÚúÛûŨũÜüŪūŬŭŮůŰűỤụŲųẀẁẂẃŴŵẄẅỲỳÝýŶŷỸỹŸÿȲȳŹźŽžŻżĲĳƏə'

**Reply by IdiotTryingToFindWay** [reply]
makes sense

**Reply by BigBobbas** [reply]
i'm just testing now... i'm in the middle of adding the config for timers and some other things like a 'beep' for wakeword detected.. 

Yes - adding the full range fixed it for me

**Reply by IdiotTryingToFindWay** [reply]
still not working. who would have thought something so small would be so annoying lol

**Reply by IdiotTryingToFindWay** [reply]
i even tried 
- platform: homeassistant
    id: humid
    unit_of_measurement: "%"
    entity_id: sensor.home_current_humidity
    internal: true

**Reply by BigBobbas** [reply]
i have a feeling the font may not support it. 
I'm just compiling with a different font .... 
and....
it works! ... using my_font2

**Reply by IdiotTryingToFindWay** [reply]
> i'm just testing now... i'm in the middle of adding the config for timers and some other things like a 'beep' for wakeword detected..
> 
looking forward to that config!

**Comment by BigBobbas** [comment]
![20240705_054452](https://github.com/BigBobbas/ESP32-S3-Box3-Custom-ESPHome/assets/150487209/e13f7fa3-ccba-4dc1-b084-9ba219610a81)

**Reply by BigBobbas** [reply]
i need to do some dusting lol ... looks bad close up like that

**Reply by IdiotTryingToFindWay** [reply]
strange.. i'm using the same font for my_fontseg3     DSEG7Classic-Regular.ttf which is the one you are using right for 2?

**Reply by BigBobbas** [reply]
no it's the consola.ttf
```yaml
  - file: "https://github.com/BigBobbas/ESP32-S3-Box3-Custom-ESPHome/raw/main/fonts/consola.ttf"
    id: my_font2
    size: 72
    glyphs:
      '&@!"''%()+=,-_.:°/$€£¥?0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyzÀàÁáÂâÃãÄäĀāĂăÅåǺǻẠạĄąÆæǼǽĆćĈĉČčĊċÇçĎďĐđÐðÈèÉéÊêẼẽĚěËëĒēĔĕĖėẸẹĘęĜĝǦǧĞğĠġĢģĤĥĦħıÌìÍíÎîĨĩÏïĪīĬĭİỊịĮįȷĴĵĶķĸĹĺĽľĻļŁłĿŀŃńÑñŇňŅņƝɲŊŋŉÒòÓóÔôÕõÖöŌōŎŏŐőỌọǪǫØøǾǿŒœŔŕŘřŖŗŚśŜŝŠšŞşȘșẞßŤťŢţȚțŦŧÞþÙùÚúÛûŨũÜüŪūŬŭŮůŰűỤụŲųẀẁẂẃŴŵẄẅỲỳÝýŶŷỸỹŸÿȲȳŹźŽžŻżĲĳƏə'
```
