### DISCUSSION TITLE
How to rectify on board temperature sensor accuracy

### DISCUSSION THREAD

**Discussion by BigBobbas** [BigBobbas/ESP32-S3-Box3-Custom-ESPHome#34] [Polls]
I'm trying to see if there is a consistent temperature difference on the majority of devices. I find that if I sit another temp sensor near the box I am getting a higher reading of around 4 degrees c. are you also seeing the same scenario?

**Comment by youkorr** [comment]
Is it possible to remove or replace it with another sensor?

**Reply by BigBobbas** [reply]
an offset can be applied in the config to make the reading correct, because of its location it reads high as it is getting heat from the rest of the device.  The reason for the poll is to see if this is the same for others and if so to find out if the difference is consistent with other users.

**Comment by geddyleefan** [comment]
I have a dedicated thermometer/humidity sensor, an Adafruit Funhouse, and the S3 all right next to each other, none show the same temperature :) The Funhouse has lights on it, so that affects the reading on it, I've tried to compensate for that, but it's inconsistent.  The S3 seems to consistently read about two degrees over the dedicated temp sensor, so at least that one is fixable.

**Reply by youkorr** [reply]
Hi to all of me it depends sometimes as the box is with a battery I can have with 100% battery a difference of 4 degrees then at 50% battery the difference is 1 degree???

**Reply by BigBobbas** [reply]
> I have a dedicated thermometer/humidity sensor, an Adafruit Funhouse, and the S3 all right next to each other, none show the same temperature :) The Funhouse has lights on it, so that affects the reading on it, I've tried to compensate for that, but it's inconsistent. The S3 seems to consistently read about two degrees over the dedicated temp sensor, so at least that one is fixable.

Thanks for your feedback.  To rectify this you can edit the sensor config to :
```yaml
sensor:
  - platform: aht10 
    i2c_id: bus_b
    variant: AHT20
    temperature:
    filters:
      offset: -2
    name: "Temperature"
    id: s3temp
    humidity:
      name: "Humidity"
    update_interval: 60s
```
I hope that helps 👍
