### DISCUSSION TITLE
Music player

### DISCUSSION THREAD

**Discussion by spasypaddy** [BigBobbas/ESP32-S3-Box3-Custom-ESPHome#51] [General]
I'm really new to editing YAMLs, especially ones as incredible as this...

is there a way to make the media card with the play/pause buttons etc control a sonos device which is already in home assistant?

this is one of my favourite things to tinker with (but havent achieved anything yet) so thanks to BigBobbas 👍 

i should add, every time i try to update IDs i get this, so i am trying
 IDs must only consist of upper/lowercase characters, the underscorecharacter and numbers. The character '.' cannot be used.

**Comment by BigBobbas** [comment]
Hi there,
i'll have a look at controlling external media for you, it should be reasonably straightforward (famous last words)
With `id:` if you stick to using an underscore to break up words, that should be fine. eg: kitchen_light that would be fine. If you mean adding entity_id: then those need to be kept exact the same as they are in HA.  id: on it's own is purley used internally by the config, so that different parts of the config can reference the id: to access and use that particular section. These are in no way related to entity_id. 

If there is anything in particular you need a hand with , please let me know so I or someone else can give you some pointers to help.

Thank you for your support! 

Many Thanks
Rob 👍

**Reply by spasypaddy** [reply]
thanks Rob!

That makes sense. I was trying to set up external media player (talk about running before i walk) and couldn't but your explanation makes sense.

I actually struggle with getting the toggles to work. This is what i have but it doesnt work. I've tested the service call in HA and it works fine

```
- platform: touchscreen
    page_id: lights_page
    id: lights1
    internal: true
    x_min: 5
    x_max: 105
    y_min: 90
    y_max: 170
    on_click:
      min_length: 10ms
      max_length: 500ms
      then:
        - homeassistant.service:
            service: light.toggle
            data:
              entity_id: light.garden_room_inside_lights
    #### make sure that the following 2 lines are uncommented and sit at the bottom of this block after your action ###
            # - display.page.show: lights_page 
            # - component.update: s3_box_lcd
```
