### DISCUSSION TITLE
Easiest way to set static IP

### DISCUSSION THREAD

**Discussion by solarjunkev** [BigBobbas/ESP32-S3-Box3-Custom-ESPHome#52] [Q&A] [answered]
Hi what is the easiest way to set static IP? Thanks

**Comment by BigBobbas** [comment, marked as answer]
Hi, the best way is to set a dhcp reservation in your router. However you can set one on the device if you wish by adding the following under `wifi:` adding your own ip, gateway and subnet.
```yaml
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.0.123
    gateway: 192.168.0.1
    subnet: 255.255.255.0
```
Cheers

Rob
