### DISCUSSION TITLE
gif in response from voice assistant

### DISCUSSION THREAD

**Discussion by youkorr** [BigBobbas/ESP32-S3-Box3-Custom-ESPHome#76] [Ideas]
I have this idea since I saw on the expressive site a video of the box3 with chatgpt with nice gif I would like to replace the fixed images of voiceassistant with an animated image

**Comment by youkorr** [comment]
I started to see what I can do here is the start of the code
```
font:
  - file: "font.ttf"
    id: my_font
    size: 20

image:
  - file: "images/frame_001.bmp"
    id: frame_001
  - file: "images/frame_002.bmp"
    id: frame_002
```
