### DISCUSSION TITLE
standby

### DISCUSSION THREAD

**Discussion by youkorr** [BigBobbas/ESP32-S3-Box3-Custom-ESPHome#8] [Ideas]
home red when you press it goes to the home page but is it possible that you press it a second time to go back to standby??

**Comment by BigBobbas** [comment]
yes, that should be something that can be done. I will add it to the list of edits to make 👍

**Reply by youkorr** [reply]
OK thanks

**Comment by youkorr** [comment]
hi I know I come back to this several times, do you have the same problem as me or is it my box that is messing up, when the screen saver is activated and the timeout to delete everything is fine with the screen saver screen is activated and the LCD screen closes off after 180s, as soon as it detects a person the screen saver turns on at 100% but does not turn off, I had to create an automation to turn off the LCD to save battery then the automation is saved as personalized???

**Comment by youkorr** [comment]
![box0](https://github.com/BigBobbas/ESP32-S3-Box3-Custom-ESPHome/assets/96953496/9858eafa-eb02-4689-b3b1-301e201bc539)

**Comment by youkorr** [comment]
![box3](https://github.com/BigBobbas/ESP32-S3-Box3-Custom-ESPHome/assets/96953496/396d0079-6d61-4f00-89ae-ffef37903ad6)

**Reply by BigBobbas** [reply]
I will have time to look into this today, just to clarify.
When all three options for screensaver are turned on. You have the following behaviour.
after 30sec = dim screen
after 180s = blank screen
On movement = Home Page 100% Brightness
after 30s = no change????
after 180s = no change???
so the screen saver only works on the first instance, then after wake it does nothing ??

Is that correct ?

**Comment by youkorr** [comment]
Thanks for replying When all three screen saver options are enabled. You have the following behavior.
after 30 seconds = dim screen
 after 180 s = screen off
Yes it works and as I get closer to the sensor I see the home screen.
screensaver option seu
after 30 seconds=low screen
As soon as I get closer = 100% brightness but does not turn off

Option scrensaver+timeout to blank the script
after 30 seconds = dim screen
 after 180 s = screen off

As soon as I get closer = 100% brightness but does not turn off

Thank you

**Comment by BigBobbas** [comment]
can you try this, it is under the binary_sensor: section towards the end of the yaml, around line no. 1307
```yaml
  - platform: gpio
    pin:
      number: GPIO21
    name: "Presence detect"
    disabled_by_default: false
    device_class: "occupancy"
    on_state:
      if:
        condition:
          - switch.is_on: s_saver_presc 
          - display.is_displaying_page: saver_page
        then:
          - display.page.show: idle_page
          - component.update: s3_box_lcd
          - light.turn_on:
              id: led
              brightness: 100%
          - script.execute: saver_enabled
        # else:      
        #   if:
        #     condition:
        #       not:
        #         display.is_displaying_page: idle_page
        #     then:
        #       - component.update: s3_box_lcd
        #       - light.turn_on: 
        #           id: led 
        #           brightness: 100%
        #     else:
        #       - display.page.show: idle_page
        #       - component.update: s3_box_lcd
        #       - light.turn_on: 
        #           id: led 
        #           brightness: 100%
        ```
if that works, you can then remove all of the commented lines if you wish.

**Comment by BigBobbas** [comment]
I have also made this change 
'Home Button' (red circle) 
press when not on home page and it will show home page.
Press when on home page will turn off screen. Change to config as follows 👍 aprox line 1295 in config
```yaml
  - platform: gt911
    name: "Home"
    index: 0
    on_press:
      if:
        condition:
          - display.is_displaying_page: idle_page  
        then:
          - script.execute: saver_enabled_manual
        else:
          - light.turn_on:
              id: led
              brightness: 100%  
          - display.page.show: idle_page
          - component.update: s3_box_lcd
```
and added this script
```yaml

  - id: saver_enabled_manual
    then:
      - if:
          condition: 
            switch.is_on: s_saver 
          then:
            - light.turn_on: 
                id: led
                brightness: 30%
            - display.page.show: saver_page
            - component.update: s3_box_lcd
      - if:
          condition:
            - switch.is_on: s_saver_mode            
          then:
            - delay: 180s
            - light.turn_off: led
    mode: restart 
```
