### ISSUE TITLE
Can't connect to ESPHome API

### ISSUE THREAD

**Issue by Gazda86** [BigBobbas/ESP32-S3-Box3-Custom-ESPHome#104]
please see the error in the picture. I would like to find a solution for this, the device is offline, does not connect to wifi. the wifi access is correct in the secret.yaml. Thank you in advance
![20241107_105647](https://github.com/user-attachments/assets/1e26006a-4945-4d60-b94f-09f6928d31d8)

**Comment by BigBobbas** [comment]
hi there , if you look in your routers interface do you see the device connected? and if so can you make a note of the IP address ?  andd add it to the config like so. (under wifi: replacing the xxx's)
```yaml
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address:  xxx.xxx.xxx.xxx
  ```

**Comment by Gazda86** [comment]
![17310114491553893450889183442105](https://github.com/user-attachments/assets/11a9ef4d-7e4b-40aa-b674-584d47ea99a2)
until the installation, I can see the device on the router as well, it connects to the wifi. after installation, unfortunately, it is already connected to wifi.
![17310112332855131548102274429945](https://github.com/user-attachments/assets/364491f1-acab-4bcc-883b-c73e099fda7c)
![17310114911219146385275193892210](https://github.com/user-attachments/assets/94d21849-2861-4b52-9b9a-746808f93ebe)

**Comment by BigBobbas** [comment]
from https://web.esphome.io connect the device using usb, then select 'logs' when the blank log screen appears, click 'reset this device' at the bottom and you should see if it tries to connect to wifi and any possible errors.

**Comment by Gazda86** [comment]
![17310452874405998583941309315484](https://github.com/user-attachments/assets/c335b3b2-9536-42e7-a91c-b641c759c1aa)


it can't connect to wifi, but my network can see it. the log file in the picture.

**Comment by BigBobbas** [comment]
can you confirm that your secrets file looks like this and that your credentials are correct including any upper and lower case letters etc.

```yaml
# Your Wi-Fi SSID and password

wifi_ssid: "your_ssid"
wifi_password: "your_password"
```
is your wifi ssid configured to be hidden?
does the ssid have any spaces or charecters in it ?

**Comment by Gazda86** [comment]
the ssid is hidden, yes, Gazda 2,4 but I have already tried Gazda 2.4.

**Comment by BigBobbas** [comment]
can you change the `wifi:` section in your config to the following
```yaml
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  ```
