### ISSUE TITLE
HA media_player.play_media Content Playback Speed

### ISSUE THREAD

**Issue by jmferris** [BigBobbas/ESP32-S3-Box3-Custom-ESPHome#111]
From HomeAssistant I am seeing a strange issue when calling media_player.play_media, where the playback speed is greatly reduced, taking almost 30 seconds to play a 5 second audio file.  I have tried this with multiple mp3 files, and they all exhibit the same behavior.  If I make the same service call to any other media_player device in Home Assistant, it plays correctly.  It is only on the ESP32-S3-Box3-Custom-ESPHome instance that I see this.

Firmware version is: V1.10.24.1

I can reproduce this in the developer tools, with the following simple YAML:

```
action: media_player.play_media
target:
  device_id: 21fceba79f050743d0f45f2076d59133
data:
  media_content_id: http://homeassistant.local:8123/local/audio/alerts/weather_alert.mp3
  media_content_type: music
  announce: true
```

Obviously, change the device_id to match a known device, and the media_content_id to point to a real MP3 file.  This is in my /config/www/local path, and plays fine via browser, through that same URL, as well.

Interestingly, if I upload the file to the local media manager, and browser to select to play the same file from the dashboard card, it plays just fine.  Initially, I found this while working on a Node-RED flow, to pre-pend a TTS message with an alert sound, due to it timing out on a link call that had a timeout duration sent to twice the length of the .mp3 file.  Since then, I have tried various methods of invoking the service call, with the same net result - only this device exhibits the behavior.

Any help would be appreciated, and a sincere thank you for a great bit of firmware for this device!

**Comment by BigBobbas** [comment]
hi there ,
 you could try increasing the sample rate in the following block to see if that helps. i'm unable to test at the moment. I know that there have been various changes in HA recently in preperation of the release of the HA voice hardware which may be related.
 ```yaml
 adf_pipeline:
  - platform: i2s_audio
    type: audio_out
    id: adf_i2s_out
    i2s_audio_id: i2s_shared
    i2s_dout_pin: GPIO15
    adf_alc: false
    dac:
      i2c_id: bus_a
      model: es8311
      address: 0x18
      enable_pin:
        number: GPIO46
        ignore_strapping_warning: true
    sample_rate: 16000
    bits_per_sample: 16bit
    fixed_settings: true
    ```
    Hope this helps.
    
    Cheers
    Rob
