### ISSUE TITLE
No screen saver after announcement

### ISSUE THREAD

**Issue by leilich** [BigBobbas/ESP32-S3-Box3-Custom-ESPHome#139]
I realized that the screen saver did not appear after an announcement from homeassistant. Seems to be a missing line at the end of the media_player-section; the line solved the problem for me.
Sorry, I do not understand the concept of git, so I chose this way to communicate the possible solution.
```
media_player:
  - platform: speaker
[...]
    on_idle:
      - script.execute: start_voice_assistant
      - script.execute: saver_enabled # this line seems to be missing
```
