### ISSUE TITLE
add home button screensaver toggle functionality

### ISSUE THREAD

**Issue by BigBobbas** [BigBobbas/ESP32-S3-Box3-Custom-ESPHome#15]
configure home button to toggle on/off screen saver

**Comment by BigBobbas** [comment]
added the following to the config
```yaml
  - platform: gt911
    name: "Home"
    index: 0
    on_press:
      if:
        condition:
          - switch.is_on: s_saver
          - display.is_displaying_page: idle_page
        then:
          - light.turn_off: led
        else:
          - light.turn_on: 
              id: led
              brightness: 100%
          - display.page.show: idle_page
          - component.update: s3_box_lcd
          - script.execute: saver_enabled
```
